### ISSUE TITLE
VertexArrayObject functions not initialized in GL 3.0 and up

### ISSUE THREAD

**Issue by floooh** [nigels-com/glew#10] opened 2014-03-16 20:44 UTC
It looks like the vertex array object function pointers (glGenVertexArrays, glDeleteVertexArrays, glBindVertexArray) are not setup as part of glewInit() on GL 3.0 and up. These functions should be available as vanilla GL functions from GL 3.0 and up (see https://www.opengl.org/registry/doc/glspec30.20080811.pdf). I noticed this on OSX when setting up a 3.2 core profile context (but on the other hand, GLEW is redundant in this scenario, since the core profile doesn't expose any extensions). It still might be a bug in GLEW though.

**Comment by MichelPaulissen** [comment] 2015-01-23 10:03
The problem is that glGetString(GL_EXTENSIONS) returns null on Intel devices that have a core profile above GL3 (it's deprecated functionality). It should use glGetStringi to query the extensions. I was going to fix it, but then I realized setting up the build environment would take too long.
I'm reverting to a compatibility context for now, but this should be fixed soon.

**Comment by stopiccot** [comment] 2015-02-07 17:33
I would vote for core context support as number one priority feature in next releases

**Comment by nigels-com** [comment] 2016-11-13 04:24
Likely resolved in GLEW 2.0.0, closing.
Thanks for the report.

**Closed by nigels-com** 2016-11-13 04:24 UTC
Labels: duplicate, enhancement
