### ISSUE TITLE
[suggest] Put the `CMakeLists.txt` file into the root directory.

### ISSUE THREAD

**Issue by hwhsu1231** [nigels-com/glew#366] opened 2022-08-18 18:34 UTC
I noticed that GLEW puts its `CMakeLists.txt` into `build/cmake` directory instead of root directory. However, `CMakeLists.txt` is put into the root directory of CMake-based projects **BY CONVENTION**.

**Comment by nigels-com** [comment] 2022-08-18 20:54
Duplicate of Issue #149

**Closed** 2022-12-31 21:56 UTC
Labels: duplicate
